# Generated by Django 4.2 on 2025-11-12 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlarmStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopped', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('target_temperature', models.FloatField()),
                ('defrost_threshold_temperature', models.FloatField()),
                ('auto_mode', models.BooleanField()),
                ('compressor_on', models.BooleanField(blank=True, null=True)),
                ('ventilation_on', models.BooleanField(blank=True, null=True)),
                ('heater_on', models.BooleanField(blank=True, null=True)),
                ('defrost_type', models.CharField(choices=[('AUTO', 'Естествено'), ('FORCED', 'Принудително')], default='AUTO', max_length=6)),
                ('temperature_low', models.FloatField()),
                ('temperature_high', models.FloatField()),
                ('evaporator_temperature_low', models.FloatField()),
                ('evaporator_temperature_high', models.FloatField()),
                ('humidity_low', models.FloatField()),
                ('humidity_high', models.FloatField()),
                ('supply_voltage_low', models.FloatField()),
                ('supply_voltage_high', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CameraReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('target_temperature', models.FloatField()),
                ('defrost_threshold_temperature', models.FloatField()),
                ('supply_voltage', models.FloatField()),
                ('evaporator_temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('defrost_type', models.CharField(choices=[('AUTO', 'Естествено'), ('FORCED', 'Принудително')], max_length=6)),
                ('auto_mode', models.BooleanField()),
                ('compressor_on', models.BooleanField()),
                ('ventilation_on', models.BooleanField()),
                ('heater_on', models.BooleanField()),
                ('status', models.CharField(choices=[('ON', 'Включен'), ('OFF', 'Изключен'), ('DEFROST', 'Обезскрежаване')], max_length=7)),
                ('problem', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='main.camera')),
            ],
        ),
        migrations.AddConstraint(
            model_name='camera',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('auto_mode', True), ('compressor_on__isnull', True), ('ventilation_on__isnull', True), ('heater_on__isnull', True)), models.Q(('auto_mode', False), ('compressor_on__isnull', False), ('ventilation_on__isnull', False), ('heater_on__isnull', False)), _connector='OR'), name='camera_auto_mode_check'),
        ),
        migrations.AddField(
            model_name='alarmstop',
            name='alarm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.alarm'),
        ),
        migrations.AddField(
            model_name='alarmstop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
